apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: semenov
spec:
  selector:
    app: hello-world-semenov
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP

